const mongoose = require('mongoose');


const statsSchema = mongoose.Schema({
    eventName: String,
    fx_ID: Number,
    player: String,
    shirt_NO: Number,
    plforn: String,
    plsurn: String,
    teamName: String,
    mins: Number,
    left_right_fx_ID: Number,
    actionRow : String,
    ID: Number,
    fx_ID_2: Number,
    right_PLID: Number,
    right_team_ID: Number,
    ps_timestamp: Number,
    ps_endstamp: Number,
    MatchTime: Number,
    psID: Number,
    period: Number,
    x_coord: Number,
    y_coord: Number,
    x_coord_end: Number,
    y_coord_end: Number,
    right_action: Number,
     metres:Number,
     play_num:Number,
     set_num:Number,
     sequence_id:Number,
     player_advantage:Number,
     score_advantage:Number,
     flag: Boolean,
     advantage:Number,
     assoc_player:Number,
     Right_Right_FXID:Number,
     Data:String,
     FxDate:Date,
     FxWeek:Number,
     FxHTID:Number,
     hometeam:String,
     FxATID:Number,
     awayteam:String,
     HTFTSC:Number,
     ATFTSC:Number,
     REFNAME:String,
     Competition_Name:String,
     action_type:String,
     qualifier_3:String,
     action_result:String,
     qualifier_4:String,
     qualifier_5:String,
     team_id:Number,
     team:String

});

module.exports = mongoose.model('Stats', statsSchema);
